### ISSUE TITLE
haru模型/01和/02子文件夹中json文件为空

### ISSUE THREAD

**Issue by BeautyyuYanli** [xiazeyu/live2d-widget-models#1]
npm包的haru模型/01和/02子文件价中json文件为空.希望能修改

**Comment by xiazeyu** [comment]
若您想要手动使用模型，请将`modelJson`设置为
`https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/01/assets/haru01.model.json`或`https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/02/assets/haru02.model.json`

`live2d-widget-model-haru@1.0.5/01/package.json`与`live2d-widget-model-haru@1.0.5/02/package.json`的作用仅为`hexo-helper-live2d`中使用

```yaml

model:
  use: live2d-widget-model-haru/01

```

时，`hexo-helper-live2d`定位`/01/assets/haru01.model.json`用。

相关代码:
https://github.com/EYHN/hexo-helper-live2d/blob/master/index.js#L145

**Comment by xiazeyu** [comment]
@BeautyYuYanli 不知道您所说的json文件为空是不是指`live2d-widget-model-haru@1.0.5/01/package.json`为空，这两个空是正常的。
