### ISSUE TITLE
模型预览

### ISSUE THREAD

**Issue by IntPtrZero** [xiazeyu/live2d-widget-models#10]
不知道选哪个模型，能添加一些截图预览更好。

**Comment by Hots-J** [comment]
> 不知道选哪个模型，能添加一些截图预览更好。

超级同意

**Comment by Patrick-Jun** [comment]
> 不知道选哪个模型，能添加一些截图预览更好。

Agree

**Comment by Chef5** [comment]
https://huaji8.top/post/live2d-plugin-2.0/
