### ISSUE TITLE
想引入其他的模型，具体该怎么操作

### ISSUE THREAD

**Issue by ZhenHe17** [xiazeyu/live2d-widget-models#11]
这个仓库还有很多模型[live2d_models_collection](https://github.com/xiaoski/live2d_models_collection)，但是格式和live2d-widget要求的格式不一样。我看了下，把资源移到assets，然后编写一个package.json就行了吗。不是很清楚具体的移植方法

**Comment by xiazeyu** [comment]
live2d-widget只需要知道模型的.model.json文件即可。具体资源的路径信息均在模型的.model.json文件中有提供
加密后的能否显示不知道
无需编写package.json，这仅仅是用于将模型单独上传至npm

在 2019-12-09 10:50:02，GeShengming <notifications@github.com> 写道：


这个仓库还有很多模型live2d_models_collection，但是格式和live2d-widget要求的格式不一样。我看了下，把资源移到assets，然后编写一个package.json就行了吗。不是很清楚具体的移植方法

**Comment by ZhenHe17** [comment]
哦哦也就是可以直接用了，谢谢啦
