### ISSUE TITLE
能把facerig的创意工坊模型移植进去？

### ISSUE THREAD

**Issue by Terli** [xiazeyu/live2d-widget-models#15]
如题

**Comment by xiazeyu** [comment]
可以 但是现在的live2d-widget.js只支持cubism 2的模型
估计有其他项目做cubism 3的支持

**Comment by Terli** [comment]
好的谢谢，试过modle1可以，标记model3的行不通。STN后缀的直接套用您的使用了，之后学习下STN文件要如何去配置出来
