### ISSUE TITLE
如果有预览就最好了

### ISSUE THREAD

**Issue by xty1992a** [xiazeyu/live2d-widget-models#2]
如题.

没有预览不好选啊~~

**Comment by Ero-Cat** [comment]
是的，求发一份预览 @xiazeyu

**Comment by 1v9** [comment]
@xty1992a @ColorfulGhost [这里](https://huaji8.top/post/live2d-plugin-2.0/) 能看个大概

**Comment by Ero-Cat** [comment]
> @ xty1992a @ColorfulGhost [这里](https://huaji8.top/post/live2d-plugin-2.0/)能看个大概

3Q 所以我觉得koharu模型最萌了！
