### ISSUE TITLE
文件名不一致

### ISSUE THREAD

**Issue by 1v9** [xiazeyu/live2d-widget-models#3]
[tsumiki.model.json](https://cdn.jsdelivr.net/npm/live2d-widget-model-tsumiki@1.0.5/assets/tsumiki.model.json) 请求的所有 f0*.exp.json 文件并不存在，本来没有发现这个问题，是在 Chrome 控制台发现了好多 404 最后找到了这里。

[tsumiki/assets/exp](https://cdn.jsdelivr.net/npm/live2d-widget-model-tsumiki@1.0.5/assets/exp/) 下的文件都是 F 开头而不是 tsumiki.model.json 里面写的 f 开头。

但是没影响我使用挂件，所以不算问题？

**Comment by xiazeyu** [comment]
文件名一个是大写的F, 一个是小写的f...

**Comment by templeorz** [comment]
大佬，更新不了！每次都是shizuku这个，但是我下载的和配置都是她哈
