### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by templeorz** [xiazeyu/live2d-widget-models#8]
大佬，更新不了！每次都是shizuku这个，但是我下载的和配置都是她哈

**Comment by xiazeyu** [comment]
Ctrl+F5刷新或者换台机子
如果都是这样那大概就是配置问题咯
也可以换换插件版本试试

**Comment by templeorz** [comment]
好的 谢谢 已经可以了，我放在了主配置文件，就好使了  谢谢




------------------ 原始邮件 ------------------
发件人: "S4kura0ne"<notifications@github.com>; 
发送时间: 2019年8月25日(星期天) 晚上8:44
收件人: "xiazeyu/live2d-widget-models"<live2d-widget-models@noreply.github.com>; 
抄送: "城南花已开"<784350547@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xiazeyu/live2d-widget-models] 大佬 (#8)




Ctrl+F5刷新或者换台机子
 如果都是这样那大概就是配置问题咯
 也可以换换插件版本试试
